# Generated by Django 2.2.4 on 2019-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='mob_no',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('MALEGAON', 'MALEGAON'), ('NASHIK', 'NASHIK'), ('JALGAON', 'JALGAON'), ('NAGAR', 'NAGAR'), ('MUMBAI', 'MUMBAI')], max_length=20),
        ),
    ]
