# Generated by Django 2.2.4 on 2019-10-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191008_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
