# Generated by Django 2.2.4 on 2019-10-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('message', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('hospital_name', models.CharField(default='', max_length=30)),
                ('blood_group', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
