# Generated by Django 2.2.4 on 2019-10-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(),
        ),
    ]
